version: "3"
services:
  nest:
    build: .
    container_name: nest
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - .env:/app/.env

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: nest-nginx
    depends_on:
      - nest
    environment:
      - NGINX_SERVER_NAME=localhost
      - NEST_HOST=nest
      - NEST_PORT=3000
      - NGINX_MAX_BODY=100M
    ports:
      - 80:80

  db:
    container_name: nest-db
    image: postgres:14
    ports:
      - 5435:5432
    env_file:
      - .env
    # environment:
    #   POSTGRES_DATABASE: nest
    #   POSTGRES_USER: nest
    #   POSTGRES_PASSWORD: nest
    #   DB_TYPE: postgres
    #   DB_USERNAME: nest
    #   DB_PASSWORD: nest
    #   DB_HOST: db
    #   DB_PORT: 5432
    #   DB_DATABASE: nest

